fix compiler warning [-Wimplicit-function-declaration]
move declaration of _byteswap_ulong from strcodec.c to strcodec.h so it is explicitly available to segdec.c

/bpvol/jxrlib/image/decode/segdec.c: In function ‘_load4’:
/bpvol/jxrlib/image/decode/segdec.c:66:12: warning: implicit declaration of function ‘_byteswap_ulong’ [-Wimplicit-function-declaration]
   66 |     return _byteswap_ulong(*(U32*)pv);
      |            ^~~~~~~~~~~~~~~